# Makefile.dep created Tue Jan 28 18:11:11 PST 2020
commands.o: commands.cpp commands.h file_sys.h util.h debug.h
debug.o: debug.cpp debug.h util.h
file_sys.o: file_sys.cpp debug.h file_sys.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp commands.h file_sys.h util.h debug.h
